CREATE TABLE security_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE bibliography_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    source_types VARCHAR(200),
    example_text VARCHAR(4000) NOT NULL,
    description VARCHAR(4000),
    target_token VARCHAR(50),
    search_pattern VARCHAR(500),
    expected_view VARCHAR(4000)
);

CREATE TABLE bibliography_validation_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total_lines INT DEFAULT 0 NOT NULL,
    error_count INT DEFAULT 0 NOT NULL,
    unknown_count INT DEFAULT 0 NOT NULL
);

CREATE TABLE bibliography_validation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    line_number INT NOT NULL,
    raw_text TEXT NOT NULL,
    source_type VARCHAR(50),
    type_detected BOOLEAN NOT NULL,
    is_valid BOOLEAN NOT NULL,
    FOREIGN KEY (session_id) REFERENCES bibliography_validation_sessions(id) ON DELETE CASCADE
);

CREATE TABLE bibliography_line_errors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id BIGINT NOT NULL,
    rule_code VARCHAR(50),
    error_index INT NOT NULL,
    error_length INT NOT NULL,
    error_message VARCHAR(255) NOT NULL,
    expected_view VARCHAR(4000),
    FOREIGN KEY (line_id) REFERENCES bibliography_validation_lines(id) ON DELETE CASCADE
);

INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (2, 'DASH_INSTEAD_OF_EM_DASH', 'Дефис вместо длинного тире', null, 'М.: Наука, 2020. — 250 с.', null, null, ' - ', ' — ');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (5, 'MISSING_DOT_DASH', 'Разделитель зон должен быть ". — " (точка, пробел, длинное тире, пробел)', null, 'Иванов И. И. Название. — М.: Наука, 2020. — 250 с.', null, null, '\.\s?[-–]\s', '. — ');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (17, 'ISSUE_FORMAT', 'Номер выпуска должен быть в формате "№ X"', 'ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST', '№ 9', null, 'ISSUE', '^[Nn]\.?\s*\d', '№ 9');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (18, 'JOURNAL_YEAR_FORMAT', 'После названия журнала должно быть ". — Год"', 'ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST', '. — 2016', null, null, ',\s*\d{4}', '. — 2016');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (10, 'PAGES_NO_DOT', 'После "с" должна быть точка', null, '250 с.', null, 'PAGES', '\d+\s+с(?!\.)', '250 с.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (14, 'YEAR_NOT_FOUR_DIGITS', 'Год издания должен быть четырёхзначным числом', null, '2020', null, 'YEAR', '^(?!\d{4}$).*$', '2020');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (19, 'DISSERTATION_PAGES_FORMAT', 'Объём диссертации: строчная "с."', 'DISSERTATION,ABSTRACT', '150 с.', null, 'PAGES', '[СC]\s*\.', 'с.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (6, 'CITY_NOT_ABBREVIATED', 'Город должен быть сокращён (М., СПб., Н. Новгород)', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,BOOK_UNDER_EDITOR,MULTIVOLUME', 'М.', null, 'CITY', '^(Москва|Санкт-Петербург|Петроград|Ростов-на-Дону|Ленинград|Нижний Новгород|Минск)$', 'М., СПб., Н. Новгород');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (21, 'MISSING_URL', 'Отсутствует URL', 'ELECTRONIC_WEBSITE,ELECTRONIC_NEWSPAPER,ELECTRONIC_JOURNAL,ELECTRONIC_PORTAL,ELECTRONIC_BOOK,ELECTRONIC_COURSE,LEGAL', 'URL: http://...', null, 'URL', '^.{0,5}$', 'URL: http://...');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (22, 'MISSING_ACCESS_DATE', 'Отсутствует дата обращения', 'ELECTRONIC_WEBSITE,ELECTRONIC_NEWSPAPER,ELECTRONIC_JOURNAL,ELECTRONIC_PORTAL,ELECTRONIC_BOOK,ELECTRONIC_COURSE,LEGAL', '(дата обращения: 01.01.2023)', null, 'ACCESS_DATE', '^.{0,5}$', '(дата обращения: ДД.ММ.ГГГГ)');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (24, 'GOST_NUMBER_FORMAT', 'Номер ГОСТа: "ГОСТ XXXX-XX"', 'GOST,GOST_FROM_COLLECTION', 'ГОСТ Р 52196–2003', null, 'GOST_NUMBER', '^(?!ГОСТ(\s+\p{L}+)?\s+\d+[–-]\d+).*', 'ГОСТ ХХХХ-ХХ');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (9, 'PAGES_LOWERCASE_S', 'Количество страниц должно быть со строчной "с."', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,BOOK_UNDER_EDITOR,MULTIVOLUME', '250 с.', null, 'PAGES', '[СC]\s*\.', 'с.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (16, 'PAGES_UPPERCASE_S', 'Страницы статьи должны быть с заглавной "С."', 'ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST,ARTICLE_COLLECTION,ARTICLE_ENCYCLOPEDIA,NEWSPAPER_ARTICLE,CHAPTER_BOOK', 'С. 2–4', null, 'PAGES', '^[сc]\.', 'С.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (28, 'DOUBLE_SPACES', 'Обнаружены двойные пробелы', null, 'Текст', null, null, '\s{2,}', 'Одиночный пробел');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (23, 'VOLUME_FORMAT', 'Номер тома должен быть в формате "Т. X"', 'MULTIVOLUME,ARTICLE_ENCYCLOPEDIA', 'Т. 2', null, 'VOLUME', '^(?!Т\.\s*\d+$).*', 'Т. 2');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (20, 'NEWSPAPER_DATE_FORMAT', 'Дата должна быть в формате "17 июня"', 'NEWSPAPER_ARTICLE,ELECTRONIC_NEWSPAPER', '17 июня', null, 'DATE', '^(?!\d{1,2}\s+\p{L}+\.?$).*', '17 июня');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (11, 'SINGLE_SLASH_INSTEAD_OF_DOUBLE', 'Название журнала должно отделяться двойной косой чертой "//"', 'ARTICLE_JOURNAL_AUTHORS_FIRST', 'Название статьи // Журнал', null, null, '(?<![А-ЯЁа-яё])(?<!/)/(?![/\d])', '//');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (25, 'PATENT_NUMBER_FORMAT', 'Номер патента: "Патент NNNNNNN"', 'PATENT', 'Патент 2187888', null, 'PATENT_NUMBER', '^(?!Патент\s+\d+).*', 'Патент XXXXXXX');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (26, 'ARCHIVE_FOND_FORMAT', 'Фонд: "Ф. NNN"', 'ARCHIVE_DOCUMENT', 'Ф. 130', null, 'FOND', '^(?!Ф\.\s*\d+).*', 'Ф. 130');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (27, 'ARCHIVE_OPIS_FORMAT', 'Опись: "Оп. N"', 'ARCHIVE_DOCUMENT', 'Оп. 6', null, 'OPIS', '^(?!Оп\.\s*\d+).*', 'Оп. 6');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (29, 'REMOVE_ISBN', 'Удалите ISBN из описания источника', null, 'Без ISBN', null, null, '(?i)ISBN[\s:]*[\d\-]+[\dXx]', 'Удалить ISBN');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (30, 'MISSING_PAGES', 'Отсутствует количество страниц', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,BOOK_UNDER_EDITOR,MULTIVOLUME', '250 с.', null, 'PAGES', '^.{0,3}$', 'XXX с.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (1, 'AUTHOR_INITIALS_SPACING', 'Инициалы автора должны быть разделены пробелом', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST,RESPONSIBILITY', 'Иванов И. И.', null, 'AUTHORS', '[А-ЯЁ]\.[А-ЯЁ]\.', 'И. И.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (3, 'AUTHOR_INITIALS_NO_DOT', 'После инициала должна стоять точка', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST,RESPONSIBILITY', 'Иванов И. И.', null, 'AUTHORS', '[А-ЯЁ]\s[А-ЯЁ]\s', 'И. И.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (31, 'AUTHOR_INITIALS_SLASH_INSTEAD_OF_DOT', 'Опечатка: слеш вместо точки в инициалах', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST,RESPONSIBILITY', 'С.', null, 'AUTHORS', '[А-ЯЁ][а-яё]?/', 'С.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (4, 'AUTHOR_SURNAME_LOWERCASE', 'Фамилия автора должна начинаться с заглавной буквы', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST,RESPONSIBILITY', 'Иванов И. И.', null, 'AUTHORS', '^[а-яё]', 'Заглавная буква');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (13, 'AUTHOR_INITIALS_NO_DOT_AFTER_FIRST', 'После первого инициала должна быть точка', 'BOOK_AUTHORS_FIRST,BOOK_TITLE_FIRST,ARTICLE_JOURNAL_AUTHORS_FIRST,ARTICLE_JOURNAL_TITLE_FIRST,RESPONSIBILITY', 'Иванов И. И.', null, 'AUTHORS', '[А-ЯЁ]\s[А-ЯЁ]\.', 'И. И.');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (32, 'PUBLISHER_CLEAN', 'Удалите служебные слова из названия издательства', null, 'Экономика', null, 'PUBLISHER', '(?i)(Издательство|Издательский\s+дом|Изд-во|Издат\.\s+дом|НКО|ФГБУН|АО|ПАО|ОАО|ЗАО|ООО|Ltd|Inc|GmbH)', 'Только название издательства');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (33, 'REMOVE_ELECTRONIC_RESOURCE', 'Удалите "[Электронный ресурс]" из описания', null, 'без [Электронный ресурс]', null, null, '(?i)(\[?Электронный\s+ресурс\]?|\[?электронный\s+ресурс\]?)', 'Удалить');
INSERT INTO bibliography_rules (id, code, name, source_types, example_text, description, target_token, search_pattern, expected_view) VALUES (34, 'MISSING_URL_FOR_ELECTRONIC', 'Добавьте URL для источника с пометкой "Электронный ресурс"', null, 'URL: http://...', null, null, '(?i)\[?Электронный\s+ресурс\]?(?!.*URL:)', 'Добавить URL: ...');
